FROM bitnami/spark:3.2.1

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libpq-dev \ 
    curl \
    libgl1 \
    libglib2.0-0

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

