services:
  minio:
    image: minio/minio:RELEASE.2024-07-26T20-48-21Z
    hostname: bigdata-minio
    container_name: bigdata-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data
    networks:
      - bigdata-network
networks:
  bigdata-network:
    name: bigdata-network
    external: true